### ISSUE TITLE
Checkpoint 'TCP packet out of state' with tag=communicate tag=network

### ISSUE THREAD

**Issue by simonsigre** [enosysau/Splunk_TA_checkpoint-opseclea_Enosys#5]
It appears that these low level (somewhat non traffic) based alarms are being tagged as 
`tag=network` and `tag=communicate` 

Example (redacted);
```
time=1563139373|loc=5713793|fileid=1563133052|action=drop|orig=192.168.0.10|i/f_dir=inbound|i/f_name=ethX-0X.XX|has_accounting=0|logId=1|log_type=connection|log_sequence_num=769|is_first_for_luuid=XXXXX|log_version=5|origin_sic_name=CN=XXXXXXXXX|uuid=<00000000,00000000,00000000,00000000>|product=VPN-1 & FireWall-1|__policy_id_tag=product=VPN-1 & FireWall-1[db_tag={XXXX-XXXX-XXXX-XXXX-XXXX};XXXX;date=1562833841;policy_name=XXXX_FW_Policy]|TCP packet out of state=First packet isn(+)t SYN|tcp_flags=FIN-ACK|src=X.X.X.X|s_port=443|dst=X.X.X.X|service=34045
```
Whilst these records do have both `dest` and `src` fields they are missing other fields (such as `proto`) I feel like these are probably better suited to be included in the IDS/IPS datamodel and setting of the `TCP packet out of state` to be the `signature` and also as this particular item states its `TCP ...` then we may even be able to infer `proto`

Thoughts?

**Comment by linsmeyerh** [comment]
CheckPoint documentation (https://supportcenter.checkpoint.com/supportcenter/portal?eventSubmit_doGoviewsolutiondetails=&solutionid=sk118415) covers the issue linked to "connection is deleted from the Security Gateway's "Connections" kernel table after receiving the TCP [FIN-ACK] packet from the Server" and "TCP [FIN-ACK] packet sent from the Client cannot be found in the Security Gateway's "Connections" kernel table" and dropped (session).

The CheckPoint community documentation (https://community.checkpoint.com/t5/General-Topics/First-packet-isn-t-SYN/td-p/7021) explains the issue associated with configuration issues (routing/session timeout) or poor application involved (less likely) and not as a security threat detection.

In my opinion, does not qualify for IDS/IPS, but I would say `Network Sessions` as Session End.

**Comment by linsmeyerh** [comment]
Final work performed removing log events with `TCP_packet_out_of_state` from being tagged as firewall and communicate.
 
The log events with `TCP_packet_out_of_state` based on the new configuration are no longer being populated into Network Traffic datamodel.

The work performed under eventtypes stanza [opsec_communicate].
